apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bhatvinay7/shortner-gitops.git
    targetRevision: staging
    path:  services/url-web
    directory:
      recurse: true    
  destination:
      server: https://kubernetes.default.svc
      namespace: shortner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true       